# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Funkwhale API is started
  ansible.builtin.service:
    name: "{{ funkwhale_api_identifier }}"
    state: started
    daemon_reload: true
  register: start_result

- name: Wait a while, so that the Funkwhale API instance can manage to start
  ansible.builtin.pause:
    seconds: 7
  when: "start_result.changed"

- name: Ensure users are created
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/util/ensure_user_registered.yml"
  with_items: "{{ funkwhale_users }}"
  loop_control:
    loop_var: user
  no_log: true
