# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Funkwhale systemd services are stopped and removed
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/remove_service.yml"
  with_items:
    - service: "{{ funkwhale_frontend_identifier }}.service"
      path: "{{ devture_systemd_docker_base_systemd_path }}/{{ funkwhale_frontend_identifier }}.service"
    - { service: "{{ funkwhale_api_identifier }}.service", path: "{{ devture_systemd_docker_base_systemd_path }}/{{ funkwhale_api_identifier }}.service" }
    - service: "{{ funkwhale_celery_worker_identifier }}.service"
      path: "{{ devture_systemd_docker_base_systemd_path }}/{{ funkwhale_celery_worker_identifier }}.service"
    - service: "{{ funkwhale_celery_beat_identifier }}.service"
      path: "{{ devture_systemd_docker_base_systemd_path }}/{{ funkwhale_celery_beat_identifier }}.service"
    - service: "{{ funkwhale_watch_imports_identifier }}.service"
      path: "{{ devture_systemd_docker_base_systemd_path }}/{{ funkwhale_watch_imports_identifier }}.service"

- name: Ensure Funkwhale container network does not exist
  when: funkwhale_container_network_deletion_enabled
  block:
    - name: Ensure Funkwhale container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ funkwhale_container_network }}"
        state: absent

    - name: Ensure Funkwhale container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ funkwhale_container_network }}
      register: network_deletion_result
      failed_when: network_deletion_result.rc > 0 and 'not found' not in network_deletion_result.stderr
      changed_when: funkwhale_container_network in network_deletion_result.stdout

- name: Ensure Funkwhale support files do not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ funkwhale_api_base_path }}/env"
    - "{{ funkwhale_api_base_path }}/labels"
    - "{{ funkwhale_frontend_base_path }}/env"
    - "{{ funkwhale_frontend_base_path }}/labels"

- name: Ensure Funkwhale local paths except data path do not exist
  ansible.builtin.file:
    path: "{{ item}}"
    state: absent
  with_items:
    - "{{ funkwhale_api_base_path }}"
    - "{{ funkwhale_celery_beat_base_path }}"
    - "{{ funkwhale_celery_worker_base_path }}"
    - "{{ funkwhale_frontend_base_path }}"

- name: Ensure Funkwhale local data path does not exist if empty
  ansible.builtin.command:
    cmd: "rmdir {{ funkwhale_data_path }}"
  register: funkwhale_data_path_deletion_result
  changed_when: funkwhale_data_path_deletion_result.rc == 0
  failed_when: false

- name: Ensure Funkwhale base path does not exist if empty
  ansible.builtin.command:
    cmd: "rmdir {{ funkwhale_base_path }}"
  register: funkwhale_base_path_deletion_result
  changed_when: funkwhale_base_path_deletion_result.rc == 0
  failed_when: false

- name: Check existence of Funkwhale local data path
  ansible.builtin.stat:
    path: "{{ funkwhale_data_path }}"
  register: funkwhale_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Funkwhale local data path
  when: funkwhale_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Funkwhale instance has been removed, some old data remains in `" + funkwhale_data_path + "`. Feel free to delete it."
        ]
      }}
